#
# roles/base/tasks
# Fred C. (W6BSD)
#
---

- name: Install the base packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - aptitude

- name: add users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    comment: "{{ item.gcos }}"
    groups: adm,sudo,plugdev,i2c,spi
    state: present
  with_items:
    "{{ accounts }}"
